version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "2024:2024"
    environment:
      - NODE_ENV=production
      - PORT=2024
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped